travis:
  secure:
    BINSTAR_TOKEN: l/Kku9jb9nIO3oTAPqk+JbnYDTsa0/HUIC06ma0LUvMn9dozz08cGfFJdP8rIsBy887tpKqZ/dPwgsZUqx9IX7N3iZllHw+jJFefZ14odTwyS8z9mrshkZO3MGkUGvw1i+Uic3B5t/yz4UOxg7B1KNqBiD9m/da2kdtzIkbfDe0QZLMQu2kwqIySoruJais0Y896261zdyPGWcHHJCf3uj6ASRybQzoAIFhkqOoErc2FfRX2FX1eeDUD0xtkfZCT6RccM8jVc7UY0S8wu9LrH+CPOQGV8Z4imnQET6eIQzNVGeX6dOQuAbZX5IkwnlSzZJxxJojD4FphsgZGYgys8nmiQtpW8lAaUsDLxdM9fwlnoBgwxftRfF+5CaePcmyDBs5QzKrpU2a0tTIhLEVrpwR0EiXMeOtLDG+mJ3mppogash68KJysuhmslOjQmzvq74hDavBZ6xXypSIf+X0fCsn/n0d3ZUteP+hs7CL//m9zu+6PUZ2HLu0E1zN39pZdmgV4Iuct75wqw1z0bFtxf5W8+TBbFOpz8ZvR3Zmxx4q54q2kINW5CXhMUcFlu15ry6tcusUS+/aW9HauGCAVhCD+xDrgCrzf7M6saXvy6Y8wpPVFqdfB/wvYqInAjCG9tSCLF7WdfHI9nW2mPxcOewfOdYmofX/HEq8anLGCqq0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
